### ISSUE TITLE
Use a single instance of the Relay Environment

### ISSUE THREAD

**Issue by VaclavSir** [kiwicom/react-native-app#101]
Currently we create a new environment every time when we call `commitMutation` or when we render `QueryRenderer`. It's not too often, but still it's not a best practice.

We should use a single instance for the whole application.

**Comment by mrtnzlml** [comment]
> We should use a single instance for the whole application.

Note: it's necessary to be careful here. There are two Environments at this moment: one for public graph paths and one for private where you need authorization. However, this should be avoidable by better Environments design because it's used only in internal query fetcher...

**Comment by mrtnzlml** [comment]
I have no idea how to fix it properly now. It's easy with one Environment (the public one) but not that easy with private one. Help wanted...

**Comment by VaclavSir** [comment]
Something like:
```
let publicEnvironment, privateEnvironment, privateToken;

function getEnvironment(accessToken: string = '') {
  if (accessToken === '') {
    if (!publicEnvironment) {
      publicEnvironment = createEnvironment();
    }
    return publicEnvironment;
  } else {
    if (accessToken !== privateToken) { 
      privateEnvironment = createEnvironment(accessToken);
      privateToken = accessToken;
    }
    return privateEnvironment;
  }
}
```
But I don't like it either, I'll keep thinking. 🤔

**Comment by mrtnzlml** [comment]
Yeah, I will have to do something like this. The thing is that with public Environment it's really trivial:

```js
export default new Environment({ ... });
```

In this case, you'll (almost) always get single instance but with the private one, you need to recreate it every time access token changes and that's tricky in JS (as you showed). I will just take few days to think about it properly because I want to make it easily testable as well... 🙂
