### ISSUE TITLE
Export boarding pass to the Apple Wallet

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#16]
https://developer.apple.com/wallet/

**Comment by dlukes** [comment]
Just out of curiosity, why is this not a desirable feature? I was going to submit a feature request precisely for this, but seeing as this issue is labeled wontfix, I assume there's no point in doing so.

**Comment by tbergq** [comment]
This is handled by the native part of our application, not by the `react-native` part of the application. 

The feature should already be a part of the kiwi.com app 🙂

**Comment by dlukes** [comment]
Thank you very much for the reply! With the knowledge that the feature should be there somewhere in the app, I actually managed to find it :)

Might I suggest that the app could make it a little more easily discoverable? When I open the booking details, the first boarding-pass-related menu item I see is *Open boarding pass*, which opens the pdf version. The pdf version has a share button, so I thought if Apple Wallet export is not listed there, the feature simply is not available.

But in the next section of *Booking details*, *Trip info*, there's a *Tickets* menu item which is subtitled *Boarding passes*, and only there do you get more info and options, including Apple Wallet export. However, it did not occur to me to investigate this further until I knew for sure (thanks to you) that the feature should be available somewhere in the app.

Or at least, since this github issue pops up pretty prominently on google when searching for "kiwi boarding pass apple wallet", this might help other people who are wondering how to do this. I've seen [complaints on-line that booking flights through Kiwi makes it impossible to retrieve mobile boarding passes (because you can't manage the flight directly)](https://www.tripadvisor.co.nz/ShowTopic-g1-i10702-k11510382-Don_t_book_Ryanair_flight_tickets_through_a_third_party-Air_Travel.html) -- this is clearly not true (cf. above), but it indicates I might not be the only person having trouble accessing the feature :)

**Comment by tbergq** [comment]
Thank you very much for your feedback, I will create an issue on our closed-source mobile repo for this, linking to your comment 😊
